### ISSUE TITLE
Settings screen

### ISSUE THREAD

**Issue by peculiaruc** [zurichat/zc_app_android#95]

**Comment by peculiaruc** [comment]
I am working on this issue

**Comment by CephasPeter** [comment]
Settings Screen has been implemented in the last [Commit](https://github.com/zurichat/zc_app_android/commit/27340f51161ffc279fa09394c9572780f4921526)
The Settings Screen can be tested [here](https://appetize.io/app/reax340m4vvcp8bgx6wn691860?device=nexus5&scale=75&orientation=portrait&osVersion=8.1).

**Comment by markessien** [comment]
This is a stand alone settings screen that does not seem to be part of any application

**Comment by CephasPeter** [comment]
Proper App Flow Has Been Added In.
All Checks has been passed
This issue was implemented by @CephasPeter

The New Testing Link Is this
https://appetize.io/app/df95r4d1vgr8q05f7zwxyeyegc?device=nexus5&scale=75&orientation=portrait&osVersion=8.1

Video Showing A Preview Of What has been done
https://user-images.githubusercontent.com/52112132/131927142-b222be6f-98f0-41de-bb76-3794991ff32a.mp4
